In [22]:
import numpy as np
x=np.array([1,2,3,4,5])
N=5

In [14]:
np.column_stack([x**(N-i-1) for i in range(N)])

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [13]:
[x**(N-i-1) for i in range(N)]

[array([  1,  16,  81, 256, 625], dtype=int32),
 array([  1,   8,  27,  64, 125], dtype=int32),
 array([ 1,  4,  9, 16, 25], dtype=int32),
 array([1, 2, 3, 4, 5], dtype=int32),
 array([1, 1, 1, 1, 1], dtype=int32)]

In [9]:
help(np.vander)

Help on function vander in module numpy:

vander(x, N=None, increasing=False)
    Generate a Vandermonde matrix.
    
    The columns of the output matrix are powers of the input vector. The
    order of the powers is determined by the `increasing` boolean argument.
    Specifically, when `increasing` is False, the `i`-th output column is
    the input vector raised element-wise to the power of ``N - i - 1``. Such
    a matrix with a geometric progression in each row is named for Alexandre-
    Theophile Vandermonde.
    
    Parameters
    ----------
    x : array_like
        1-D input array.
    N : int, optional
        Number of columns in the output.  If `N` is not specified, a square
        array is returned (``N = len(x)``).
    increasing : bool, optional
        Order of the powers of the columns.  If True, the powers increase
        from left to right, if False (the default) they are reversed.
    
        .. versionadded:: 1.9.0
    
    Returns
    -------
    out : ndar

In [10]:
np.vander(x,N,increasing=False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [23]:
def fun1(x,N):
    return np.column_stack([x**(N-i-1) for i in range(N)])
fun1(x,N)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [24]:
x=[10,20,30,40,50,60,70,80,90,100]

In [50]:
def fun2(x,k):
    ma=[]
    for i in range(len(x)-k+1):
        avg=[]
        for j in range(k):
            avg.append(x[i+j])
        ma.append(int(np.average(avg)))
    return ma

In [52]:
fun2(x,5)

[30, 40, 50, 60, 70, 80]